name: CI

on:
  push:
    branches:
      - main

jobs:
  job1:
    permissions:
      contents: write  # required to push to the repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action Bot"

      - name: Push commit
        run: |
          git -b test-pr checkout
          echo "Hello, GitHub! to test PR creation" > hello.txt
          git add hello.txt
          git commit -m "test-pr: Modified hello.txt"
          git push
